application:
  author: Georges WAKEU
  demo: ${app.name.demo}
  title: Administration service
  version: 0.0.1

server:
  port: 8020

spring:
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /actuator

logging:
  level:
    com:
      netflix: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"

