application:
  author: Georges WAKEU
  demo: ${app.name.demo}
  title: Administration service
  version: ${version}

spring:
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /actuator


