application:
  author: Georges WAKEU
  demo: ${app.name.demo}
  title: Category service
  version: ${version}

spring:
  datasource:
    url: jdbc:h2:mem:categories
  graphql:
    graphiql:
      enabled: true
  h2:
    console:
      enabled: true

logging:
  level:
    com.axion.wfutur.controllers: DEBUG