# Application config
application:
  author: Georges WAKEU
  demo: ${app.name.demo}
  title: Student service
  version: ${version}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/students
    username: keycloak
    password: keycloak
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
